import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'reference/overview',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'reference/getting-started'},
      items: [
        'reference/getting-started/installation',
        'reference/getting-started/first-ui',
        'reference/getting-started/events-and-state',
        'reference/getting-started/forms-basics',
        'reference/getting-started/api-integration',
        'reference/getting-started/ajax-form',
        'reference/getting-started/page-control',
        'reference/getting-started/debugging-and-tips',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference/classes'}],
    },
  ],
};

export default sidebars;
